### ISSUE TITLE
Handle pubdate of Wed, 26 Jun 2024 15:00:57 +0000

### ISSUE THREAD

**Issue by greggles** [v-p-b/rss2bsky.py#2]
I got close to running this today, but am getting an error from this line of code:

```
        rss_time = arrow.get(item["published"])
```

Here's the tail end of the stack trace:

```
  File "/Users/greggles/projects/rss2bsky.py/path/to/venv/lib/python3.12/site-packages/arrow/parser.py", line 206, in parse_iso
    raise ParserError(
arrow.parser.ParserError: Expected an ISO 8601-like string, but was given 'Wed, 26 Jun 2024 15:00:57 +0000'. Try passing in a format string to resolve this.
```

I believe from [pages like this](https://stackoverflow.com/questions/11993258/what-is-the-correct-format-for-rss-feed-pubdate) and [this](https://whitep4nth3r.com/blog/how-to-format-dates-for-rss-feeds-rfc-822/) quoting the RSS 2.0 specification that is a valid pubDate.

It seems arrow has a constant for `FORMAT_RFC822` but this uses 2 digit dates while the feed I'm trying to parse is 4 digit dates.

**Comment by v-p-b** [comment]
[57e154b](https://github.com/v-p-b/rss2bsky.py/commit/57e154bc28229e74732465d278b26d4f1e647d2e) should fix this.
