### ISSUE TITLE
Exception because RSS item has no 'content'

### ISSUE THREAD

**Issue by mactrash** [v-p-b/rss2bsky.py#5]
```
Traceback (most recent call last):
  File "/mnt/HDD2/rss2bsky.py/rss2bsky.py", line 171, in <module>
    run()
  File "/mnt/HDD2/rss2bsky.py/rss2bsky.py", line 145, in run
    content = item["content"][0]["value"]
              ~~~~^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.12.0/lib/python3.12/site-packages/feedparser/util.py", line 113, in __getitem__
    return dict.__getitem__(self, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'content'
```

**Comment by v-p-b** [comment]
1. Please provide descriptive titles for GitHub issues that describes the problem at hand so others can find it (I'm fixing this for you)
2. Can you share the URL of the RSS feed you are trying to consume for debugging?

**Comment by mactrash** [comment]
@v-p-b please forgive me, and maybe forget the issue maybe because my RSS don't have content.

**Comment by v-p-b** [comment]
No problem, feel free to reopen with some sample input if you think it should be parsed correctly yet it isn't!
